### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BenGOsborn** [Torque-Money/Torque-Frontend#19]
- [x] Add option for different networks and a config for all including the fork
- [x] Instead of using whales, instead use a router to swap FTM for tokens
- [x] Update the frontend to change config and explorer based on chain ID

**Comment by BenGOsborn** [comment]
Fix the issue with the repayments too

**Comment by BenGOsborn** [comment]
Change name to add liquidity (means I need to change docs and website too)

**Comment by BenGOsborn** [comment]
I believe the problem is that the address is being called before the correctly implemented tokens have been set by the correct config change ????

**Comment by BenGOsborn** [comment]
Fix #1: Pass the token through to the protocol updates instead of the address + remove config
Fix #2: Multiply utilization rate by borrowing for weights + update docs
Fix #3: Add etherscan account for automatic verification with hardhat
